language: java
jdk: oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_e73fb50d032a_key -iv $encrypted_e73fb50d032a_iv
  -in assistant-domoticz-b2ccb70ff6dd.json.enc -out assistant-domoticz-b2ccb70ff6dd.json
  -d

deploy:
  provider: gae
  keyfile: assistant-domoticz-b2ccb70ff6dd.json
  project: assistant-domoticz
  config: target/appengine-staging/app.yaml
  on: production