language: java
jdk: oraclejdk8
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_e73fb50d032a_key -iv $encrypted_e73fb50d032a_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- cp application.properties src/main/resources/application.properties
- cp application.properties src/test/resources/application.properties
- cp assistant-domoticz-report-state.json src/main/resources/assistant-domoticz-report-state.json
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export
  CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud version
- gcloud --quiet components install app-engine-java
- gcloud --quiet auth activate-service-account --key-file assistant-domoticz-cli.json
- gcloud config set project assistant-domoticz
addons:
  sonarcloud:
    organization: seblaporte-github
    token:
      secure: UQFLDhZp73NvVcjJmTb2SRhQM9FXPJ0h1DuCN4IPTxDParf0ZSZFZfpGDQowVl2bd8Neos65Hth5GRDgnBOocRbGWv1DqcOhA5wjp0LvOYxGB05u78wbw3kJNSEeaMz4W8YW25SnrLB2iQX8lghOLmkRBQu1ez45mQu5fRlm9yJ/KKkmU6yBbkDYiD+ju0c/ZVNCsm262wq0fApC2Lw37VkRkPe1ZyNJOR5doNhTOK6HUMrhN4YkpGp2Nmm5p2B+efmIlAaZM/D64+NdV1CHuqh8Ac99/w92Zg7Y3t4TQ++/Z2Pc4i9BmYdeCGAHNZvWzu7R3s6d4M74drjWIzaKDjWdXBZcwcvmwTAPMakkn6S5+0SsNa7rUqlS9uVtbYVwAkaLTB9DD3+a0pPcRoZ/6N0ALI2LAARHY5pgZx9PpsijBG+xl+Ty1aF2m/kyEgXijZuou/wejuKFUrQuI/leXELuIMWB9zQPw6Hvx9yIeUoLFV/0JMJJpeSIy28iGzm8lBNO3x88J/9+TcyRts1/sWznOTfReDtLpX/NYsQz1AB+A34cDLXtmDkDNY8UWxijoSDDYuOy4xL+k4xzwzHE/gLB3jE30IyFZ6U74uPPj4UwKkPLLjQpDnlEkr+2h6qU/X16Adul316qAiQ1m4LEI+SerxFrKwUMf+gyAhI/m4c=
script:
- mvn appengine:deploy -DskipTests
- mvn sonar:sonar
notifications:
  slack:
    on_start: always
    secure: wlGlYpR6uy7uKd6LtBepVn8Gu7dH5YLVNVOK3zrBHhPPNZnjLU5Jk4urH9b27zqMZnZsnTbOSFreOx2ztQ0sN/L8pGVbWB1Ln9c+Lc/NRXVZS01UskidSAW8py74ictNacttd4ySvTNh3VYGTzvWRnZLSXs3TEOYqjn6/usPOWb6lDPy8Ye+hQChTOKQI7q6oT6WixnLA5p0qRK4jexy/3WoUsTwdD3+HPIcgjgDJu+kp53+G2wTFXx6GyDgf/DS6B3g8pWk3AKwGR/nhIdklJpA+U8p5VqHSalE7x9+44x9tojHguOHHmx8C3106kMvxdw0G+DIaqblJf85jzV9S1sez36i+VpndLZQS8VB9aaoOPq/INjP27PIFOvuz9VhVAFhF1WukX79M/eFpe9nUIinsUPa7UYDoWio66LD8fwC6G9FZdsrD8MuotZIsIGVNUuRbHjxAMj6Vp6f87QYCZ4XsifyxF3VfszxrgmLX6ye3UwQ9dI8HNdICtpEYe2JUioUfW/UA2GdF91gwdAFaH7bR/bCh2GUNnpY/qajcO21EUiJyZieQ9pVzbyDRmidkYle4wvXtRLKD12LYu4vd0knciB7F0DKT5HT2t09lQl6PyBElstgOps5yiz1ch45LBnFu5vZ6VPKqtBxF0e8YHdziBuC4iBft5O2de1zvDA=
