language: java
jdk: oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_e73fb50d032a_key -iv $encrypted_e73fb50d032a_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- cp application.properties src/main/resources/application.properties
- cp application.properties src/test/resources/application.properties
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export
  CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud version
- gcloud --quiet components install app-engine-java
- gcloud --quiet auth activate-service-account --key-file assistant-domoticz-b2ccb70ff6dd.json
- gcloud config set project assistant-domoticz
script:
- mvn test -B
- mvn appengine:deploy
